title: test-styles-new-staging
hero_image: images/banner.png
description: test-styles-new-staging description
version: 4
listed: false
copyedit: false
last_tested: "2019-10-28"
steps:
  - title: "Tasks Examples"
  - title: "Code Blocks Examples"
  - title: "Scratch 3 Tests"
  - title: "This is a Challenge!"
    challenge: true
  - title: "Print/Screen Test Blocks"
  - title: "Lost in Space example"
