title: Test styles
hero_image: images/banner.png
description: Test out styles
theme: violet
published: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
listed: true
duration: 1
steps:
  - title: Tasks Examples
